### ISSUE TITLE
Question: how does Genrich determine the reference genome?  

### ISSUE THREAD

**Issue by mchimenti** [jsh58/Genrich#1]
In the docs you write: 
"Genrich runs very quickly but uses a considerable amount of memory. For starters, it requires 3 bytes for every base-pair of the reference genome, i.e. ~9GB for a human sample. The number of input files has little effect on memory, but certain analysis options (especially the option to remove PCR duplicates) can greatly increase the memory usage, particularly with large SAM/BAM input files. See above for an example."

Does Genrich determine the reference genome information from the SAM header?  

Does Genrich download a reference genome from somewhere while doing its peak calling?  

thanks, Michael

**Comment by jsh58** [comment]
Michael,

Thanks for the question.  Yes, Genrich determines the reference genome length from the SAM/BAM header, as described [here](https://github.com/jsh58/Genrich#genomelen).  It does not use any other information about the reference genome, and it does not download anything, ever.

John Gaspar

**Comment by mchimenti** [comment]
John, thanks for your response.  I ask b/c I'm trying to incorporate genrich into a NextFlow-based ATAC-seq pipeline.  It errors out on a very small test dataset with status "137": job killed for insufficient memory.  

What would you say is the minimum memory allocation for a genrich job, even on a "toy" dataset?  Should I allocate at least 9GB as you say in the docs, even for a small test set?

**Comment by jsh58** [comment]
For human samples, you will need at least 9GB because of the genome length.  The size of the dataset does not affect the size of the genome.
