### ISSUE TITLE
About ATAC-seq

### ISSUE THREAD

**Issue by AlexWanghaoming** [jsh58/Genrich#10]
Dear developer,
    I have a fastq (totally 84192124 reads) from ATAC-seq. When call peaks using that, I get about 12000 peaks with commond：` Genrich -t file_sort.bam -o file.peaks -r -j `
   Now, if I shuffle the fastq/Bam file into two replicates, I only get 2000 peaks each replicates. I do not know why, could you help me?

Thanks
Alex

**Comment by jsh58** [comment]
Alex,

Genrich follows a specific procedure when analyzing multiple replicates, as described [here](https://github.com/jsh58/Genrich#replicate).  This procedure is based on the assumption that the replicates are real, not artificially created.  So it is not surprising that there are different peaks called after artificially creating two replicates.

John Gaspar

**Comment by AlexWanghaoming** [comment]
Hi John, 
Thanks for your reply. I meant that I split fastq/bam reads randomly into two files and only input one of them to Genrich so that Genrich do not know it is a replicate of the two files. However, I only get 2000 peaks with a replicate, why it is much smaller than 12000.

**Comment by jsh58** [comment]
With fewer reads, there is less power to detect peaks, so that's not surprising.  Of course, in general we cannot generate more reads and guarantee more peaks will be called, since there will be more artifacts (PCR duplicates).
