### ISSUE TITLE
link for awk command does not work

### ISSUE THREAD

**Issue by ntsopoul** [jsh58/Genrich#100]
how can I make a .bed file out of this output?

chr1	3052596	3052915	peak_0	1000	.	442.801178	5.126367	-1	205
chr1	3059562	3059884	peak_1	1000	.	466.875092	4.341691	-1	77
chr1	3445843	3446234	peak_2	1000	.	1799.574707	9.660245	-1	187

The link to the awk description does not work

Thanks!

**Comment by jsh58** [comment]
I have updated the link to the awk reference.  Sorry for any inconvenience.
