### ISSUE TITLE
Removing PCR duplications gets more peaks ? 

### ISSUE THREAD

**Issue by akhst7** [jsh58/Genrich#101]
Hi, I run genrich with or without -r option as follows;

#!/opt/homebrew/bin/zsh

Genrich -t /Volumes/MySlateDrive/snatac_snRNAseq_pbmc3k/atac_Solo.out/sortbyname.atac_SoloAligned.bam \
		 -E /Volumes/MySlateDrive/blacklist/black.list.hg38.bed \
		 -o /Volumes/MySlateDrive/peaks.pbmc3k/generich/peak.generich.bed \
		 -j \
		 -v \
		 -r \
It turns out that a -r option gives more peaks than without -r option as follows;

```
wc -l peak.generich.bed                                                                              [~]
   56128 peak.generich.bed
wc -l peak.generich.nodup.bed                                                                              [~]
   57234 peak.generich.nodup.bed
```
Why does removing PCR duplicates increase the number of peaks ? I thought it was an opposite way around.

**Comment by jsh58** [comment]
There is not a simple relationship between removing PCR duplicates and the number of peaks called.  In general, it is advisable to remove PCR duplicates, unless there is a concrete reason to believe that reads are being falsely identified as duplicates.

For additional discussion of the relationship between numbers of reads and peaks, see #11 and #33.

**Comment by akhst7** [comment]
OK I will dig a bit deeper
