### ISSUE TITLE
HowTo call peaks from bigwig files?

### ISSUE THREAD

**Issue by malcook** [jsh58/Genrich#103]
I am involved in a collaboration in which .bam files are apparently no longer available and only bigwig files can be found.  Do you have any advice/strategy as to whether Genrich can be used to call peaks from them?  I fully understand there may be multiple reasons why one should not want to do this, but still, here we are.  Thanks!

**Comment by jsh58** [comment]
Thanks for the question.  No, Genrich cannot call peaks from bigwig files.  Even in `-P` mode, Genrich requires that the input log file have *p*-/*q*-values, which a bigwig file won't have.

**Comment by keenhl** [comment]
You can convert bigwig to bedgraph, then do peak calling with MACS.
