### ISSUE TITLE
IGV and Genrich issues

### ISSUE THREAD

**Issue by ChakrabortyJC** [jsh58/Genrich#106]
Hello

I have called ATAC peaks using Genrich. 
The command was Genrich  -t input.bam  -o sample.narrowPeak  -j   -r  -e chrM  -v

When I am checking the peaks in IGV, some of the called peaks were showing no enrichment in the bw files. What went wrong?

**Comment by jsh58** [comment]
With the limited information you have provided, it is impossible to provide a reasonable answer.  Many things *could* have gone wrong.
