### ISSUE TITLE
Peaks failed to be detected

### ISSUE THREAD

**Issue by dariober** [jsh58/Genrich#11]
This issue may be related to #4 and #10. Like #4, I downsampled a bam file and found no peaks with default settings. While I understand that fewer reads lead to reduced power, I think that at least in my case the downsampled bam has still plenty of reads (I'm working with a small genome). Here's some detail using Genrich 0.5.

* Analysis of full file:

```
Genrich -j -t tmp2.full.bam -o tmp2.full.narrowPeak -v -k tmp2.full.bedgraph
Processing experimental file #0: tmp2.full.bam
... 
  BAM records analyzed:    9151902
    Paired alignments:     9145680
    Unpaired alignments:      6222
  Fragments analyzed:      4572840
    Full fragments:        4572840
    ATAC-seq cut sites:    9145680
      (expanded to length 100bp)
- control file #0 not provided -
  Background pileup value: 46.034389
Peak-calling parameters:
  Genome length: 18780606bp
  Significance threshold: -log(q) > 1.301
  Min. AUC: 20.000
  Max. gap between sites: 100bp
Peaks identified: 1058 (328845bp)
```

* Analysis of downsampled file (about 1/3 of original)

```
Genrich -j -t ip2.tmp.bam -o tmp2.narrowPeak -v -k tmp2.bedgraph
Processing experimental file #0: ip2.tmp.bam
...
  BAM records analyzed:    3177951
    Paired alignments:     3175766
    Unpaired alignments:      2185
  Fragments analyzed:      1587883
    Full fragments:        1587883
    ATAC-seq cut sites:    3175766
      (expanded to length 100bp)
- control file #0 not provided -
  Background pileup value: 15.986792
Peak-calling parameters:
  Genome length: 18780606bp
  Significance threshold: -log(q) > 1.301
  Min. AUC: 20.000
  Max. gap between sites: 100bp
Warning! All q-values are 1
Peaks identified: 0 (0bp)
```

This is a peak identified in the full file:

```
chr01	44739	45129	peak_0	1000	.	765.545837	8.982409	5.334011	266
``` 

and these are the pileup files in the peak region (full: [peak.full.bedgraph.gz](https://github.com/jsh58/Genrich/files/3085838/peak.full.bedgraph.gz), 
downsampled: [peak.bedgraph.gz](https://github.com/jsh58/Genrich/files/3085839/peak.bedgraph.gz)). It seems to me that also the downsampled file has plenty of reads to call the peak... Any thoughts?

**Comment by jsh58** [comment]
I have many thoughts, and will start with just a few:
* First of all, thank you for including the verbose outputs (edited for clarity!), the bedgraph file chunks (edited for brevity!), the references to previous issues, and the version of Genrich (0.5).  A **model** question!
* From the verbose outputs, we can see that the `Background pileup value` dropped from 46.0 to 16.0 (ratio 2.88, dotted line in the graph below).  However, the ratio of treatment pileup values decreased by varying amounts in different genomic regions (graph below).  This is expected, of course, but can lead to additional variability when comparing the subset to the full dataset.
![pileup_ratio](https://user-images.githubusercontent.com/4921955/56245981-bf14ef00-606e-11e9-84fe-81df869cc4e7.png)
* The -log(*p*) values are almost always larger for the full dataset vs. the subset (graph below).  The -log(*q*) values must have followed a similar pattern (in fact, *all* of the *q*-values were 1 with the subset (`Warning!`)).  So we would expect more peaks to be called with the full dataset than with the subset (in your case, [and in others](https://github.com/jsh58/Genrich/issues/10)).
![pvals](https://user-images.githubusercontent.com/4921955/56247436-bcb49400-6072-11e9-9660-87cc4b9fc5c9.png)
* The question then is: **should** the -log(*p*) values be larger for the full dataset?  I would argue **yes**.  But, the full argument requires a separate post...

**Comment by jsh58** [comment]
Before I get to the full argument, I should point out that all versions of Genrich prior to v0.5 used a different null statistical model, and I expect that those versions of Genrich would call nearly identical peaks after downsampling.  In fact, [that was one of the reasons for using the exponential distribution as the null model](https://github.com/jsh58/Genrich/blob/14cfb31f9dee82475b8e19bc5a318fc7fe7ce5eb/README.md#pvalue):
> Therefore, multiplying x [the experimental pileup value] and β [the control pileup value] by the same factor results in the same *p*-value, which implies that the *p*-values are robust to sequencing depth artifacts.

I liked this property of the exponential distribution, and that fact that it was very convenient to work with.  However, convenience is not a sufficient justification, and **wanting something to be true doesn't make it true**.  After [an extensive review of control samples from ChIP-seq experiments](https://github.com/jsh58/Genrich#pvalue), I had to admit that the exponential was a *poor* match to observed control pileup distributions.  And, [to quote Richard Feynman](https://www.brainyquote.com/quotes/richard_p_feynman_160383):
> It doesn't matter how beautiful your theory is, it doesn't matter how smart you are. If it doesn't agree with experiment, it's wrong.

So, the exponential distribution was out, and [the log-normal distribution was in](https://github.com/jsh58/Genrich#pvalue). 

Now, as you have observed in your downsampling example, it is *not* a property of the log-normal distribution (at least the way Genrich implements it) that the *p*-values will be necessarily stable at different sequencing depths.  As a simple example, the -log(*p*) value for an experimental pileup value of 15 and a control pileup value of 5 is 1.29, but it increases to 1.38 with pileups of 30 and 10 (twice the depth).

Although I was skeptical of this outcome, lengthy discussions with my (former) boss (@tsackton) gradually convinced me that it was not only justified, but actually desirable.  Here is the argument:
* The *p*-value is **not** strictly a measure of the magnitude of the difference between experimental and control pileup values.
* In general, the *p*-value is the probability that we would observe the measured value (or a more extreme value) under the null model.  As such, it is a reflection of our beliefs about the observed values and the system.
* Our beliefs *do* change at different sequencing depths.  In the above example, we may be confident that 15 is significantly more than 5, but our confidence increases if we sequence at twice the depth and observe the same magnitude of difference.  That is reflected in the increased -log(*p*) value.

I hope that helps.  If you aren't convinced, you can always try [an earlier version of Genrich](https://github.com/jsh58/Genrich/releases/tag/v0.4), but this isn't recommended.  Instead, you may want to try altering the [peak-calling parameters](https://github.com/jsh58/Genrich#peakcalling), as [previously recommended](https://github.com/jsh58/Genrich/issues/4).

**Comment by dariober** [comment]
Hi- Thanks for the useful discussion. I'm perfectly fine with the idea that lower sequencing depth gives less confidence and with the idea of having no peak being called. 

I guess my original question could be rephrased as *what is the motivation behind the parameter values of the lognormal distribution?* Looking at the function [calcPval](https://github.com/jsh58/Genrich/blob/master/Genrich.c#L1608) I see that the mean is the average depth (squared and divided by sqrt(sd+mu) if the average sequencing depth is > 7). 

The standard deviation is calculated from the mean regardless of the effective dispersion observed in the control and/or treatment file. I suppose these choices have been empirically obtained from reviewing published datasets?

> The p-value is not strictly a measure of the magnitude of the difference between experimental and control pileup values.

Indeed, that's pretty much why I asked #3.

**Comment by jsh58** [comment]
The best explanation for the *p*-value calculation of Genrich is [in the README](https://github.com/jsh58/Genrich#pvalue).  The `calcPval()` function in the code looks strange, because the *p*-value calculation in Genrich is adapted from `R` code, and the parameterization of `plnorm()` in `R` is slightly strange (see [this post](https://msalganik.wordpress.com/2017/01/21/making-sense-of-the-rlnorm-function-in-r/) for a good explanation).

The control/background pileup value is used to calculate both parameters (&mu; and &sigma;) of the log-normal, because, at a given base of the genome, that is the only value we have.  Fortunately, the transformations of that value into the two parameters produced a reasonable match to the pileup distributions of the ChIP-seq control samples I evaluated.
