### ISSUE TITLE
All qvalue are -1  in narrowPeak

### ISSUE THREAD

**Issue by pengxin2019** [jsh58/Genrich#110]
Hi,
Thanks for developing this tool.
I am using Genrich to process my ATAC data. I  have 9  replicates for treatment group  and 8 for control group. Here is my command to run Genrich:
```
Genrich \
-t $treat_dir/$t1,$treat_dir/$t2,$treat_dir/$t3,$treat_dir/$t4,$treat_dir/$t5,$treat_dir/$treat6,$treat_dir/$treat7,$treat_dir/$treat8,$treat_dir/$treat9 \
-o bowtie_Sscrofa11.sorted.by.name.no.MT.t.treat.replicates.c.notreat.replicates.narrowPeak \
-c $notreat_dir/$notreat1,$notreat_dir/$notreat2,$notreat_dir/$notreat3,$notreat_dir/$notreat4,$notreat_dir/$notreat5,$notreat_dir/$notreat6,$notreat_dir/$notreat7,$notreat_dir/$notreat8 \
-b bed.file -R PCR.duplicates -r -e MT -j -v

```

I was expecting to avoid IDR calculation by inspecting the q value. however, it looks like all q value are -1 in narrowPeak output file. Can you give me any suggestions?
<img width="807" alt="Screenshot 2024-02-16 at 11 36 38 AM" src="https://github.com/jsh58/Genrich/assets/54915282/d958152b-1f18-41bd-a43f-d094141b97a4">

Thanks
Best
Penny

**Comment by malcook** [comment]
Hi Penny, 

I'm not the genrich author, but I thought I'd chime in since I use it to analyze atac data.

First, note that the manual [reads](https://github.com/jsh58/Genrich?tab=readme-ov-file#peak-calling-parameters): "If a -q threshold is not specified, q-values are not calculated (reported as -1). "

In any case, in my opinion you should not use -c, which should be reserved for ChIP-seq input controls.

Instead, You should:

 -  run Genrich twice, once for your treatment group and once for the control.  (FWIW, I use q=
 - merge the peaks produced from the two runs into a "reference peak" file 
 - evaluate the reference peak file for differential chromatin accessibility using, e.g., diffBind or (my preferred) csaw.

Thoughts?

**Comment by pengxin2019** [comment]
Hi malcook,
Thanks for your kind prompt comments and pointing out i should not use `-c` flag which I was not aware of.

It definitely sounds promising to me. I  will run Genrich for treatment group and control group using `-t `flag, respectively.  Hopefully I will be able to see q value for each of output.  Then I can merge two narrowPeak results.

By the way, do you think its convincing enough to say my replicates are consistent with each other by having q value < 0.05  in treatment/control group?  I meant without calculating IDR.

I will let you know if it does not work!

Thanks again
Penny

**Comment by pengxin2019** [comment]
Hi,
I did avoid using -c flag for my ATAC data and called peaks for treatment and control groups, respectively. Here is the code for my treatment group:

```
Genrich \
-t $treat_dir/$treat1,$treat_dir/$treat2,$treat_dir/$treat3,$treat_dir/$treat4,$treat_dir/$treat5,$treat_dir/$treat6,$treat_dir/$treat7,$treat_dir/$treat8,$treat_dir/$treat9 \
-o bowtie_Sscrofa11.sorted.by.name.t.treat.9.replicates.narrowPeak \
-b treat.9.replicates.bed.file -R treat.9.replicates.PCR.duplicates -r -e MT -j -v

```
But the qvalues are still all -1. Any comments?
<img width="820" alt="Screenshot 2024-02-16 at 2 39 02 PM" src="https://github.com/jsh58/Genrich/assets/54915282/c53e1105-c5d2-452c-8300-348332fcc2b3">

Thanks
Penny

**Comment by jsh58** [comment]
As @malcook correctly pointed out, from the manual:

> If a `-q` threshold is not specified, q-values are not calculated (reported as `-1`).

**Comment by malcook** [comment]
Hi again,

You should expect to get -1 q-values given that the manual [reads](https://github.com/jsh58/Genrich?tab=readme-ov-file#peak-calling-parameters): "If a -q threshold is not specified, q-values are not calculated (reported as -1). "

**Comment by pengxin2019** [comment]
Thanks for your patience. For some reason I misread the description about q value thus I did not get the result as what I wanted. Thanks for pointing it out.

Which threshold of q values do you recommend? I wanna go with 0.05 by my intuition but I do not know whether it will make me loose most of my peaks or not. I might have to consider 0.1 if its the case.

**Comment by pengxin2019** [comment]
Thanks for your patience. For some reason I misread the description about q value thus I did not get the result as what I wanted. Thanks for pointing it out.

Which threshold of q values do you recommend? I tried to not set q value, set q value as 1, set q value as 0.05, respectively in my command.  Here is a summary of detected peaks in narrowPeak:


<img width="773" alt="Screenshot 2024-02-17 at 8 12 39 PM" src="https://github.com/jsh58/Genrich/assets/54915282/ba8a477a-dfe4-441b-ba21-791f22adaa89">



I have 2 questions in terms of table above.
1. I am surprised to see a higher number of detected peaks after setting q value cutoff as either 1 or 0.05  than not setting up q value cutoff. Can you help me to understand why it happened?
2. whats the way to interpret the q values/ columns in narrowPeak. Here is the narrowPeak file having  0.05 as q value cutoff. But all  q values (9th column) in this file are greater than 0.05 which is confusing to me. Whats the correct way to relate the q values in 9th column to the q value cutoff in the command?

<img width="772" alt="Screenshot 2024-02-17 at 8 16 36 PM" src="https://github.com/jsh58/Genrich/assets/54915282/b46212a3-f1df-419e-887b-4b5d9f42e83e">

Thanks for your patience

**Comment by jsh58** [comment]
The original issue of *q*-values being -1 has been addressed, multiple times.  If you have a different question, even after reviewing the README and previous issues, then please open a new Issue.
> Any question, concern, or bug report about the program should be posted as an [Issue](https://github.com/jsh58/Genrich/issues) on GitHub. Before posting, please check previous issues (both Open and Closed) to see if your issue has been addressed already. Also, please follow these [good GitHub practices](https://hackernoon.com/45-github-issues-dos-and-donts-dfec9ab4b612).
