### ISSUE TITLE
Bedgraph-ish files

### ISSUE THREAD

**Issue by vanottee** [jsh58/Genrich#12]
Dear Genrich development team - 

First off, very nice program....thanks for all your efforts.

I am trying to figure out if the bedgraph-ish output is normalized between samples? For example, I have 2 ctrl and 2 experimental ATAC datasets. I run each through Genrich separately (NOT combined) and get the resulting bedgraph output for each (i.e. 4 separate bedgraph files). After converting this to bigwig format I have been trying to quantify 'total peak size' at given coordinates between all 4 samples. However, I am trying to determine if these values may be influenced by overall read-depth of the 4 samples? My understanding is that 'background' pileup is dependent on overall read depth/size/etc and so the final bedgraph is directly comparable between samples?

Thanks!

Eric

**Comment by jsh58** [comment]
Eric,

It is not clear which of the `dataValue` fields of the bedgraph-ish files you are using to compare among the samples, nor is it clear what exactly you are trying to calculate ('total peak size'?).

In any case, none of the bedgraph-ish `dataValue` fields is normalized.  The [background pileup calculation](https://github.com/jsh58/Genrich#pileup) does depend on overall read depth, as you state.

John Gaspar

**Comment by vanottee** [comment]
Thanks John -

I am using multiBigwigSummary (
https://deeptools.readthedocs.io/en/develop/content/tools/multiBigwigSummary.html)
to calculate the signal for a given set of coordinates. That is, I define
the regions with a bed file, and then the pileup values within that region
are calculated.

I saved the first 4 columns of the bedgraph-ish output to generate the
bigwig file, which I then use for the multiBigwigSummary.

It is good to know that the bedgraph file is not normalized, as this will
impact my downstream counts.

Thanks,

Eric
