### ISSUE TITLE
Multiple replicate files

### ISSUE THREAD

**Issue by tcolston** [jsh58/Genrich#13]
Does someone have an example of input format for multiple replicate files? I have tried passing:

./Genrich -c null -t file.bam, file2.bam, file3.bam, file4.bam -o file_joint_called_genrich_narrowpeak.bed -f file_peak.log -j  -y  -r -v 

as well as:

./Genrich -c null -t "file.bam" "file2.bam" "file3.bam" "file4.bam" -o file_joint_called_genrich_narrowpeak.bed -f file_peak.log -j  -y  -r -v 

and both return the error: "Error! file2.bam,: unknown command-line argument"

The following will run but is only analyzing the last file specified:

./Genrich -c null -t file.bam -t file2.bam -t file3.bam -t file4.bam -o file_joint_called_genrich_narrowpeak.bed -f file_peak.log -j  -y  -r -v 

I am using Genrich version 0.5

thanks in advance!

**Comment by dariober** [comment]
At a glance, there should be no space after each comma or use single quotes to list space-separated files. E.g.

```
./Genrich -t file.bam,file2.bam,file3.bam,file4.bam ...
#OR 
./Genrich -t 'file.bam file2.bam file3.bam file4.bam' ...
```

**Comment by tcolston** [comment]
Thank you! That resolved the issue.
