### ISSUE TITLE
Genrich vs MACS2 or HMMRATTAC for ATAC-Seq

### ISSUE THREAD

**Issue by jdidion** [jsh58/Genrich#15]
I am looking to use Genrich for some ATAC-Seq analysis, but also see that you have a preprint describing an improved version of MACS2. Do you still recommend to use Genrich over MACS2? I also noticed Tao Liu has a new ATAC-specific peak caller (HMMRATAC) - do you have any opinions on that tool, or benchmarks vs Genrich? Thanks!

**Comment by jsh58** [comment]
John,

Thanks for the question.  I recommend Genrich for ATAC-seq, and this is reflected in the updated version of the [ATAC-seq guidelines](https://informatics.fas.harvard.edu/atac-seq-guidelines.html#peak), in particular the section "Interpretation of alignments suitable for ATAC-seq", Figure 4, and the following paragraph.

The [improvements made to MACS2](https://github.com/jsh58/MACS/commits/master) were to overcome some of its major bugs.  They did not rectify its limited, inflexible alignment parsing.

I do not have any benchmarks of HMMRATAC.  My opinion of it is low.

John Gaspar

**Comment by dktanwar** [comment]
I was about to post the same question and found that @jdidion already posted it yesterday 👍

I wonder if your benchmarking of Genrich vs MACS2 could be made available. Sorry, I tried to find for a paper, but, unable to locate any.

In the preprint of HMMRATAC, authors showed that it is better than MACS2

**Comment by jsh58** [comment]
This is a work in progress.  At this point, the best way to understand the differences between Genrich and MACS2 is by reading the [ATAC-seq guidelines](https://informatics.fas.harvard.edu/atac-seq-guidelines.html#peak) (as recommended above), and the description of the [ATAC-seq mode](https://github.com/jsh58/Genrich/blob/master/README.md#atacseq) of Genrich.
