### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by bigmonty12** [jsh58/Genrich#18]
Hello,

I'm a beginning bioinformatician and have really appreciated all the work you've done for the community! I have tried getting Genrich to work but always get an error that says "Segmentation fault: 11" no matter the parameters. I've tried deleting and recloning. Every time I try to compile the program, I do get a bunch of the same warnings but am completely unfamiliar with C and do not know how to proceed with them (warning: format '%ld' expects argument of type 'long int', but argument 6 has type 'int64_t {aka long long int}' [-Wformat=]
). Perhaps this is wherein the issue lies. 

Any help and advice that you have in regards to this issue would be greatly appreciated!

Thank you,
Austin

**Comment by jsh58** [comment]
Austin,

Without knowing the details, I would suggest running [`valgrind`](http://www.valgrind.org/downloads/current.html#current), as mentioned in response to issue #16.  That's a good way to track down a segfault.  Another option is `gdb`.

John Gaspar

**Comment by bigmonty12** [comment]
Hi John,

After trying to run Genrich with lldb, this is the output.

* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x7ffeee6e7838)
    frame #0: 0x000000010000f6f8 Genrich`readBAM(in=0x0000000100202ce0, line="@HD", aln=0x00007ffeefbff540, readName="", totalLen=0x00007ffeefbff5d8, unmapped=0x00007ffeefbff4d8, paired=0x00007ffeefbff4dc, single=0x00007ffeefbff4e0, pairedPr=0x00007ffeefbff4e8, singlePr=0x00007ffeefbff4ec, supp=0x00007ffeefbff4f0, skipped=0x00007ffeefbff4f4, lowMapQ=0x00007ffeefbff4f8, minMapQ=0, xcount=0, xchrList=0x0000000000000000, xBedLen=0, xBed=0x0000000000000000, secPair=0x00007ffeefbff4fc, secSingle=0x00007ffeefbff500, orphan=0x00007ffeefbff4e4, chromLen=0x00007ffeefbff4b4, chrom=0x00007ffeefbff538, singleOpt=false, extendOpt=false, extend=0, avgExtOpt=false, unpair=0x00007ffeefbff548, unpairMem=0x00007ffeefbff4b8, asDiff=0, atacOpt=false, atacLen5=100, atacLen3=0, bed=File @ 0x00007ffeefbff2d0, bedOpt=false, gzOut=false, ctrl=false, sample=0, dupsOpt=false, dups=File @ 0x00007ffeefbff300, dupsVerb=false, readPr=0x00007ffeefbff550, readMemPr=0x00007ffeefbff4c0, readDc=0x00007ffeefbff558, readMemDc=0x00007ffeefbff4c4, readSn=0x00007ffeefbff560, readMemSn=0x00007ffeefbff4c8, table=0x00007ffeefbff568, tableMem=0x00007ffeefbff4cc, tableSn=0x00007ffeefbff570, tableSnMem=0x00007ffeefbff4d0, order=0x00007ffeefbff578, order0=0x00007ffeefbff580, order1=0x00007ffeefbff588, order2=0x00007ffeefbff590, qual=0x00007ffeefbff598, qual0=0x00007ffeefbff5a0, qual1=0x00007ffeefbff5a8, qual2=0x00007ffeefbff5b0, arrMem=0x00007ffeefbff4d4, countPr=0x00007ffeefbff504, dupsPr=0x00007ffeefbff508, countDc=0x00007ffeefbff50c, dupsDc=0x00007ffeefbff510, countSn=0x00007ffeefbff514, dupsSn=0x00007ffeefbff518, errCount=0x00007ffeefbff51c, verbose=false) at Genrich.c:4993
   4990	  int32_t n_ref = readInt32(in, true); // number of ref sequences
   4991	  int idx[n_ref];  // index of reference sequences into *chrom array
   4992	  for (int i = 0; i < n_ref; i++) {
-> 4993	    int32_t len = readInt32(in, true);
   4994	    if (len < 1 || len > MAX_SIZE)
   4995	      exit(error("", ERRBAM));
   4996	    for (int j = 0; j < len; j++) {
Target 0: (Genrich) stopped.

I honestly have no idea what any of this means and am unfortunately not well-versed in debugging. Could you help me understand this?

Thank you,
Austin

**Comment by jsh58** [comment]
I do not understand it either; I am not familiar with `lldb`.

You can try posting the first few lines of your SAM/BAM file generated from these commands:
```
samtools view -h <BAM> | head -n5
od -tx4 <BAM> | head -n5
```

Also, please read [this](https://hackernoon.com/45-github-issues-dos-and-donts-dfec9ab4b612).

**Comment by bigmonty12** [comment]
Thank you for the article to read. I will try to keep that all in mind.

I used lldb because I couldn't get gdb or valgrind to work. There seems to be an issue with them working on the newest version of macOS Mojave so I tried a recommendation of lldb. 

"samtools view -h <BAM> | head -n5" produces:
@HD	VN:1.0	SO:queryname
@SQ	SN::1539792_tblastxwrap_masked	LN:141
@SQ	SN::1539770_tblastxwrap_masked	LN:123
@SQ	SN::1539791_tblastxwrap_masked	LN:165
@SQ	SN::1539790_tblastxwrap_masked	LN:171

"od -tx4 <BAM> | head -n5" produces:
0000000          04088b1f        00000000        0006ff00        00024342
0000020          5b8c2171        b71dcecd        6e97450d        4890a5df
0000040          b4abcfea        368ba2e8        40a06145        f457c657
0000060          8bad145b        e49076c4        7936f249        0b9dccb6
0000100          788f0ef8        19d6b972        28a43c8a        f1fd2352

**Comment by bigmonty12** [comment]
Hi John,

I was able to figure out the issue. Turns out there was a problem with the Drosophila index that I used to align with bowtie2. After switching to a different index, the issue resolved itself and Genrich was able to run without a hitch.

Thank you for your help!
Austin
