### ISSUE TITLE
Unequal number of treatment and control files

### ISSUE THREAD

**Issue by dariober** [jsh58/Genrich#2]
Hi- First off, thanks a lot for releasing Genrich! I'm having a go with it and my first impression on ATACseq data is very good when compared to the traditional MACS2. I have a few questions which I may post in separate issues, any advice is most welcome. Here's the first one...

I have 3 replicates for ATACseq treatment but only 2 replicates for input. How is it best to analyse this case given that the docs say *multiple replicates can be listed [...] in the same order as the experimental files. Missing control files should be indicated with null*. I'm running Genrich as:

```
Genrich -j -t a.bam,b.bam,c.bam -c c1.bam,c2.bam -o test ...
```

This gives sensible results but I'm not sure how Genrich is handling the replicates...

**Comment by jsh58** [comment]
Thanks for the question.

When multiple control files are provided, Genrich analyzes them pairwise with the experimental files.  That is, with your above command, it analyzes `a.bam` vs. `c1.bam`, and then `b.bam` vs. `c2.bam`, and then `c.bam` by itself.

If `c1` and `c2` were inputs for *all* of the experimental samples, and *not* specifically paired with `a` and `b`, it would be preferable to merge the control BAMs (by `samtools merge`), and then use the merged BAM as the control for each experimental sample (e.g. `-c d.bam,d.bam,d.bam`).

**Comment by dariober** [comment]
Thanks! That makes sense, I haven't repeated the analysis yet but I'll do shortly.
