### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [jsh58/Genrich#20]
Are you planning to release a conda recipe (any time soon). Do you have any objections if I release one? 

I, however, won't be maintaining it.

**Comment by jsh58** [comment]
Thanks for your interest.  I do not have an objection.  Couple things to keep in mind.:
* I will be modifying the code and making a new release, sometime in the next week or two.
* `./Genrich -h` returns `EXIT_FAILURE`, not 0

**Comment by Maarten-vd-Sande** [comment]
It's online!
https://anaconda.org/bioconda/genrich
Send me a ping when v0.6 is released and I'll update it
