### ISSUE TITLE
ATAC-seq mode shifted the reads +4 bp for the +strand and -5 bp for the -strand

### ISSUE THREAD

**Issue by ShuangHe33** [jsh58/Genrich#22]
Thank you for your great tool.
In the original paper for ATAC-seq, the authors shifted the reads +4 bp for the +strand and -5 bp for the -strand: http://www.nature.com/nmeth/journal/v10/n12/full/nmeth.2688.html 
 I just wonder that if  the Genrich considered the Tn5 shifting internally in the -j mode. 
Thank you in advance!

**Comment by jsh58** [comment]
Yes, this was included in the [most recent commit](https://github.com/jsh58/Genrich/commit/23cd42cfc305ca4d477cb6fb20e4e62eec572d81), 1 week ago.  The shifting is actually +5/-5 to maintain symmetric intervals.  I'll be making a new release soon.

**Comment by ShuangHe33** [comment]
> Yes, this was included in the [most recent commit](https://github.com/jsh58/Genrich/commit/23cd42cfc305ca4d477cb6fb20e4e62eec572d81), 1 week ago. The shifting is actually +5/-5 to maintain symmetric intervals. I'll be making a new release soon.

Thanks, I'll look forward for the new release!

**Comment by jsh58** [comment]
Here is the new release: [Version 0.6](https://github.com/jsh58/Genrich/releases/tag/v0.6)
