### ISSUE TITLE
Genrich for single-end ATAC-seq data

### ISSUE THREAD

**Issue by ShuangHe33** [jsh58/Genrich#24]
Thank you for the great tool Genrich. I have tried Genrich for paired-end ATAC-seq data and it worked very well to me. 

I wonder whether the ATAC-seq mode is suitble for single-end ATAC-seq, since the cut sites only exsit in 5' end and I noticed that the '-y' option can analyze intervals centered on cut sites the 5' ends of unpaired alignments, so could the '-y' option work for the single-end data?

If not, is it  compare for two biological data (one sequenced by 150bp pair-end and annother 51bp single-end) being called peak by two different tools (with different models)?

Thank you  in advance !

**Comment by jsh58** [comment]
I think this was addressed in #8, as well as the last section of #6.  If not, please clarify.
