### ISSUE TITLE
Genrich peak calls with and without control sample

### ISSUE THREAD

**Issue by codingforwork** [jsh58/Genrich#28]
Hi, 

I was wondering how the normalization works if you only input experimental or only input control file for peak calling?

My goal is to look at them separately and see what is enriched in control and experimental samples. But I also want to look at differential peaks between them. 

What would you recommend for how about I go about doing this analysis?

Thank you.

**Comment by jsh58** [comment]
Thanks for the question.

First of all, [Genrich *requires* an experimental input](https://github.com/jsh58/Genrich#required-files), so you would need to specify the input control file as the "experimental input" for the second run.

For downstream analysis, I recommend you look into [bedtools](https://bedtools.readthedocs.io/en/latest/index.html) and the answer to #19.

**Comment by codingforwork** [comment]
Okay, got it. Thank you.
