### ISSUE TITLE
Post-hoc filtering of peaks

### ISSUE THREAD

**Issue by dariober** [jsh58/Genrich#3]
Hi again- I'd like to ask advice about filtering peaks after a run. 

* The q-value seems a suitable target for filtering. However, I imagine that a threshold suitable for *x* replicates is no longer applicable for a different number of replicates since the p- or q-value can only get smaller when more replicates are combined via Fisher's method.

* Is the *average AUC* (5th column) or *AUC* (7th column) a better choice? (Since *average AUC* is capped to 1000 it may not be a good option)

* Alternatively, it would be great if Genrich could give the enrichment of the peak region relative to the surrounding region (similar to MACS, I think). This would give an intuitive parameter to rank peaks and filter them. With replicates, this enrichment could be reported as average +/- some measure of dispersion. 

* Loosely related: Is there any advantage in setting a stringent threshold for AUC or q-value via the `-q` and `-a` rather then filtering post-hoc?

Thanks again!

**Comment by jsh58** [comment]
Answers below.
<br>

> * The q-value seems a suitable target for filtering. However, I imagine that a threshold suitable for x replicates is no longer applicable for a different number of replicates since the p- or q-value can only get smaller when more replicates are combined via Fisher's method.
> * Is the average AUC (5th column) or AUC (7th column) a better choice? (Since average AUC is capped to 1000 it may not be a good option)

If you are investigating broad peaks, the total AUC is likely a better choice, since it indicates the total significance.  With narrow peaks, the average AUC is more informative.  By the way, to avoid the 1000 maximum, you can calculate the average AUC using `awk` on the peak file (`$7 / ($3 - $2)`).

It is not the case that *p*- or *q*-values can *only* get smaller with more replicates.  This is not a characteristic of Fisher's method.
<br>

> * Alternatively, it would be great if Genrich could give the enrichment of the peak region relative to the surrounding region (similar to MACS, I think). This would give an intuitive parameter to rank peaks and filter them. With replicates, this enrichment could be reported as average +/- some measure of dispersion.

I am unsure of how to calculate such a value, and I do not know of any such calculation in MACS2.
<br>

> * Loosely related: Is there any advantage in setting a stringent threshold for AUC or q-value via the `-q` and `-a` rather then filtering post-hoc?

Some researchers (most?) do not have the time, inclination, and/or ability to filter post-hoc.  They just want an answer and move on.  A stringent threshold gives them an answer.

**Comment by dariober** [comment]
> you can calculate the average AUC using awk on the peak file ($7 / ($3 - $2)).

Cool- makes sense and I'll inverstigate.

> It is not the case that p- or q-values can only get smaller with more replicates. 

True, my bad - I should have checked this before. This makes Genrich even more appealing!

> Some researchers (most?) do not have the time, inclination, and/or ability to filter post-hoc. They just want an answer and move on. A stringent threshold gives them an answer.

Mmmm... Fair enough - although I would argue that peak calling is one of those exercises where some manual inspection is more often than not necessary to get good results. But anyway, that's a different topic...

Thanks again for your attention!

**Comment by malcook** [comment]
> I am unsure of how to calculate such a value, and I do not know of any such calculation in MACS2.

I expect the @dariober  was referring to macs2's computation of slocal and llocal background as described in [Build local bias track from control](https://github.com/macs3-project/MACS/wiki/Advanced:-Call-peaks-using-MACS2-subcommands#Step_4_Build_local_bias_track_from_control).

Does such an approach not make sense  in the context of Genrich's approach to peak finding, @jsh58 ?

**Comment by dariober** [comment]
Hi- I ended up writing a script that returns the log2 fold-change enrichment of peaks over the input. Script is [genrich_logfc.py](https://gist.github.com/dariober/8ef8435eba4f9668bd6437382221b3fb) if anyone wants to give it try. 

```
./genrich_logfc.py -h
usage: genrich_logfc.py [-h] --bedgraph FILE [--narrowPeak FILE] [--version]

Calculate the log2 fold enrichment of target intervals using the read depth 
profile from Genrich.

If the target intervals are is the narrowPeak file from Genrich, the output has header:

    #chrom       
    start  
    end    
    peak_id     
    score   
    strand 
    auc          
    pvalue       
    fdr          
    summit 
    logfc:avg            # LogFC averaged across samples
    logfc:<input.bam.1>  # logFC of input sample 1, 2,... N
    logfc:<input.bam.2>  #
    logfc:<input.bam.N>  #

* MEMO: Execute Genrich -k option to produce the bedgraph profile of read depth

* Requires bedtools

* Tested with Genrich v0.6.0

optional arguments:
  -h, --help            show this help message and exit
  --bedgraph FILE, -b FILE
                        Input bedgraph from Genrich
  --narrowPeak FILE, -n FILE
                        Input peak file in bed format. Typically this is the narrowPeak
                        file from Genrich [-]
  --version, -v         show program's version number and exit
```

The calculation of logFC is fairly simple being:

```
logfc = log2(depth / avg_depth) - log2(depth_ctrl / avg_depth_ctrl)
```

where `depth` is the read depth at the summit of the peak, `avg_depth` is the average read depth of the experimental sample, `depth_ctrl` is the average read depth in the peak region in the control sample, and `avg_depth_ctrl` is the average depth of the control sample.

From a quick comparison, the results are quite similar to MACS fold-enrichments and they make sense when looking at them in a genome browser. In practice, I find this logFC more meaningful for filtering and ranking peaks than p-value or AUC.

**Comment by wqiudao** [comment]
genrich_logfc.py  --bedgraph *_pileup_p.bed   --narrowPeak *.narrowPeak


log： *_pileup_p.bed ， use this output  -k  <file>       Output bedgraph-ish file for pileups and p-values
