### ISSUE TITLE
Error! cannot open file for writing

### ISSUE THREAD

**Issue by lindsaynhayes** [jsh58/Genrich#31]
I am getting the above error message when I run genrich in ATAC mode and try to write log or bed files using -f, -k, and -b. I am running for 6 replicates. 
I initially tried: 

`${gen_path}/./Genrich -t ${in_path}/S22.query.bam,${in_path}/S33.query.bam,${in_path}/S36.query.bam,${in_path}/S39.query.bam,${in_path}/S45.query.bam,${in_path}/S54.query.bam -o {out_path}/CON.P4.narrowPeak -v -j -e chrM -f {out_path}/CON.bed -k {out_path}/CON.pileup.bed`

but got that `Error! {out_path}/CON.pileup.bed: cannot open file for writing` so I thought since I had replicates maybe the `-f` was causing problems so I removed it, but got the same error message. 

Then I changed the filename to `-k {out_path}/CON.log` but got same error message.

Finally, I tried `-b {out_path}/CON.bed` but still got the same error message. 

Do I need to specify a temporary file location to write these output files on slurm? Is there a    `-tmp` command available?

Thanks for your advice!
Lindsay

**Comment by jsh58** [comment]
Lindsay,

Thanks for the question.  I think there are two possibilities:
* `{out_path}` does not exist
* you do not have write permission to `{out_path}`

Also, Genrich does not write any temporary files.

**Comment by lindsaynhayes** [comment]
I specified the output path. It works when I run one sample, but when I run all 6 then I get the error. Maybe I need to request more memory when I run the job I will try that. Thanks for your help.

**Comment by jsh58** [comment]
Sorry, that's `${out_path}`.  You were missing **$**.

**Comment by lindsaynhayes** [comment]
ahhh.. that's a stupid mistake. thanks!

Lindsay
