### ISSUE TITLE
Input control DNA

### ISSUE THREAD

**Issue by keenhl** [jsh58/Genrich#32]
According the documentation, input control samples are not required to run Genrich.  My question is two fold:  how does the Genrich algorithm deal with not having a reference control and, importantly, does having a control sample significantly improve the performance of Genrich.  Thank you for your help. 

Optional files

 -c  <file>       Input SAM/BAM file(s) for control sample(s)

**Comment by jsh58** [comment]
Thanks for the questions.  The method for calculating the control pileup value, with or without a control sample, is explained [here](https://github.com/jsh58/Genrich#pileup).  Having a control sample helps to limit false positive peaks, such as high mappability regions that show enrichment under any condition.
