### ISSUE TITLE
Have you considered poisson distribution for q-value calculation?

### ISSUE THREAD

**Issue by NyxSLY** [jsh58/Genrich#34]
Have you considered poisson distribution for q-value calculation? Is your current method better?

**Comment by jsh58** [comment]
I don't understand the question.  Please clarify.

**Comment by NyxSLY** [comment]
Sorry, I didn't read the p-value calculation part in detail. You mentioned that it was better than Poisson distribution.

"Earlier versions of Genrich (prior to v0.5) used the exponential distribution for the null model. Although this distribution has some convenient properties (continuous, one-parameter, -log10(p) ∝ x / β), the study described above showed that the exponential distribution was a good fit to the control pileup distribution only occasionally. However, this was still better than the Poisson distribution, which is frequently used as a null model in genomics software but was a good fit to the control pileup distribution never."
