### ISSUE TITLE
Question regarding read depth for control samples in ChiPseq

### ISSUE THREAD

**Issue by linelieblein** [jsh58/Genrich#35]
I have earlier used Genrich to analyse our ATACseq data and I am now in the process of preparing samples to analyse histone marks in different tissues of salmon. I have a good idea of the number of reads I need for the immunoprecipitated samples , but  I am not sure what read depth I need for the input control samples. 

Since I am going to use Genrich to analyse the native chip samples, do you have any recommendation concerning the sequencing depth of the input control samples. I am asking because I think the different peak callers might have different preferences for the amount of reads from the control samples versus the experimental samples.

Thanks in advance, 
Best, 
Line Lieblein Røsæg

**Comment by jsh58** [comment]
Thanks for the question.  Ideally, the control samples would be sequenced to the same depth as the experimental samples.  However, as described in the [README](https://github.com/jsh58/Genrich#pileup):
```
Note that control pileups are scaled to match the experimental, based on the total sequence information in each.
```
Therefore, variability in sequencing depth is accounted for by Genrich.  Its verbose output will indicate the scaling factor.
