### ISSUE TITLE
Genrich Publication

### ISSUE THREAD

**Issue by elenichri** [jsh58/Genrich#36]
Hello. I am about to use Genrich for calling my peaks but I would like to better understand how the tool works first. Is there any respective publication?

**Comment by jsh58** [comment]
There is not yet a publication.  A complete description of how Genrich works is provided in the [README](https://github.com/jsh58/Genrich/blob/master/README.md).  If anything is not addressed there or in the [Issues](https://github.com/jsh58/Genrich/issues), please open a New issue.

**Comment by elenichri** [comment]
I see, thank you very much.
