### ISSUE TITLE
Follow Up: Genrich with reads from a tiny subset of genome #29 

### ISSUE THREAD

**Issue by vanottee** [jsh58/Genrich#37]
Dear Genrich team - 

I am wondering what chromosomes I am missing to exclude the majority of the genome from my analysis? Similar to question 29, I am trying to run my analysis on only a subset of the genome (~75Kb). However, because of my bam header, I am also getting misleading data due to the size of the genome being considered during analysis. I have used both the -e and -E functions to try and eliminate every possible region of the genome (except my 75Kb) and it still shows the genome length as ~1.6x10^8 in length. I have attached a screenshot that includes the regions I am eliminating from analysis.
![Capture](https://user-images.githubusercontent.com/49768200/67132126-374e9f80-f1cd-11e9-8961-534dacdfd776.PNG)

**Comment by jsh58** [comment]
At a first glance, I would guess `chrm3` is the issue.

**Comment by vanottee** [comment]
Obvious, oops, sorry for the bother
