### ISSUE TITLE
Peaks identified: 0

### ISSUE THREAD

**Issue by torfinnnome** [jsh58/Genrich#4]
Hi,

We're trying out Genrich for atac-seq analysis, and so far it looks very promising, but for some samples we get zero peaks. What could be the reason for this?

$ samtools sort -O SAM -n input.bam | Genrich -t - -o output.narrowPeak -m 20 -j -v
Warning! Read J00146:93:H2TF2BBXY:5:2228:14336:48491 prevented from extending past 43943985 on ssa27
Warning! Read J00146:93:H2TF2BBXY:7:1215:1336:6202 prevented from extending below 0 on ssa01
  SAM records analyzed:   37592534
    MAPQ < 20:             6054055
    Paired alignments:    29711690
      "orphan" alns:       6057892
    Unpaired alignments:   1826789
  Fragments analyzed:     11826899
    Full fragments:       11826899
    ATAC-seq cut sites:   23653798
      (expanded to length 100bp)
- control file #0 not provided -
  Background pileup value: 0.789905
Peak-calling parameters:
  Genome length: 2967030735bp
  Significance threshold: -log(q) > 1.301
  Min. AUC: 20.000
  Max. gap between sites: 100bp
Peaks identified: 0 (0bp)

**Comment by jsh58** [comment]
Thanks for the question.  It is difficult to answer specifically without a lot more information, but here are a few ideas:
* It *could* be the case that there are no open regions.
* It *could* be the case that the open regions are in repeats, and you are filtering sequence reads from those regions with `-m 20`.
* It *could* be that the statistical threshold is too high.  You could try lowering the AUC threshold (`-a`), increasing the *q*-value threshold (`-q`), and/or using a *p*-value threshold (`-p`).

Also, `"orphan" alns` are a problem.  See the last item [here](https://github.com/jsh58/Genrich#warning).
