### ISSUE TITLE
`genrich -y` on single-end chip without replicates emits q-value of -1 across the board

### ISSUE THREAD

**Issue by malcook** [jsh58/Genrich#41]
By my reading of [q\-value calculation](https://github.com/jsh58/Genrich#qvalue), a q-value should still be computed in such cases.

**Comment by jsh58** [comment]
A little further down in the [README](https://github.com/jsh58/Genrich#peakcalling), it is stated:

* If a `-q` threshold is not specified, *q*-values are not calculated (reported as `-1`).
