### ISSUE TITLE
Error! 'x': unknown value type in BAM auxiliary field

### ISSUE THREAD

**Issue by alund1394** [jsh58/Genrich#42]
Hi,

I am using Genrich in ATAC-seq mode for reads aligned with Bowtie2. 

(I am using the pipeline described here: https://informatics.fas.harvard.edu/atac-seq-guidelines.html)

I was able to generate a narrowPeak file successfully with one data set, but now I am getting the error 'x': unknown value type in BAM auxiliary field. 

Thanks!

**Comment by jsh58** [comment]
Thanks for the question.  This is an ununusual error, especially with a bowtie2-produced BAM file.  According to the [SAM spec](https://samtools.github.io/hts-specs/SAMv1.pdf) (Sections 1.5 and 4.2.4), `x` is definitely not a valid value type.

Let's see if we can extract some of the offending records.  Please post the result of this command:
```
$ samtools view <BAM> | grep -m5 ':x:'
```
