### ISSUE TITLE
Pre-marked duplicate read removal

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [jsh58/Genrich#48]
I quickly scanned the source code, but it seems that genrich includes all reads, and ignores whether a read is a duplicate or not:

> read is PCR or optical duplicate (0x400)

Am I correct in my understanding? Is it possible to use this flag instead of checking again what are duplicates?

**Comment by jsh58** [comment]
Thanks for the question.  Genrich does not analyze alignments already marked as duplicates.  It also skips supplementary and low quality alignments ("not passing filters").  In verbose mode, these will show up in the counts.

**Comment by Maarten-vd-Sande** [comment]
Thanks for answering so fast!
