### ISSUE TITLE
strand / orientation information

### ISSUE THREAD

**Issue by vicenciooostra** [jsh58/Genrich#5]
Hi,

I ran Genrich and it seems to work great! 

However I was wondering whether Genrich provides strand / orientation information for the peaks. 

In my output file, all peaks in the sixth column had just a dot (i.e. no orientation). In the README.md the fields of the output file are explained. For this field, it simply gives the dot (no orientation) as an example of the content of this field, so I wondered whether Genrich can give + or - orientation, and why I'm not getting that output. 

I mapped with Bowtie2, using standard parameters, and I'm using Genrich in ATAC seq mode. Commands are pasted below. I got 378 peaks for a single sample sequenced at 10M, with genome size of 0.5Gb, paired-end reads.

Kind regards,
Vicencio

bowtie2 -p 7 --very-sensitive  -k 10  -x mygenome.fasta  -1 $inputfile1  -2 $inputfile2  -S $samfile
samtools view -bS $samfile | samtools sort -n -@ 6 - $bamfile
Genrich -t $bamfile -o $genrichfile -b $bedfile -j -y -r -e MT_scaffold1 -v

**Comment by jsh58** [comment]
Vicencio,

Thanks for the question and for using Genrich.  Genrich does not provide strand information, and that field of the output is always `.`.  With paired-end sequencing, I do not know how to call a strand for a peak, nor what that would actually mean biologically.  Perhaps you could clarify what insight you are trying to gain from this information with ATAC-seq.

John Gaspar

**Comment by vicenciooostra** [comment]
Hi John,

thanks very much, that clarifies it. I was just wondering why there was an empty column in my output data. 

Cheers,
-v
