### ISSUE TITLE
PCR duplicates detected from different Genrich runs

### ISSUE THREAD

**Issue by elenichri** [jsh58/Genrich#50]
Hello!
I am mapping my trimmed Fastq files to the human genome hg38 using bowtie2. Then I use Genrich to call peaks and mark the PCR duplicates. I then remove the duplicates from my .bam files using the pcrDup file generated by Genrich. I was wondering whether I get different pcrDup files for different Genrich parameters, not related to the duplicates...for example if I change the threshold of the q-value or the auc, do I end up with a different set of PCR duplicates?

Thank you in advance!

**Comment by jsh58** [comment]
Thanks for the question.  Alignment parsing is entirely separate from peak-calling, so changing peak-calling parameters has no effect on the PCR duplicates identified by Genrich.  See also the description of the `-X` option [here](https://github.com/jsh58/Genrich#misc).

**Comment by elenichri** [comment]
Thank you very much!
