### ISSUE TITLE
Mem limit error

### ISSUE THREAD

**Issue by Ru194** [jsh58/Genrich#53]
Hi, I am working with a BAM file of size 9.1GB for ATAC peak calling. I ran the job with 50 GB of memory and still got the following error: 

TERM_MEMLIMIT: job killed after reaching LSF memory usage limit.
Exited with exit code 130.

Could you please help me to figure out what's wrong?

Thank you

**Comment by jsh58** [comment]
It is unlikely, though not impossible, that Genrich is using that much memory for an input BAM of that size.  Are you sure that it is actually doing that?  If so, you can check #9 for some ideas of reducing memory usage.

**Comment by moqri** [comment]
Similar issue with two BAM files of 5+5 GBs and 50 GB of memory:
`Error! Cannot allocate memory`

Will try with 100GB and update if the error persist

**Comment by moqri** [comment]
Resolved with higher memory. Also, it seems each run needed ~ 15  GB of memory and I was running a few runs together so that might be the reason I got the error.
