### ISSUE TITLE
Large difference in Peak number.

### ISSUE THREAD

**Issue by Adnanhashim** [jsh58/Genrich#56]
Hi, 
First of all thanks for a wonderful tool. I have ATAC seq data with 2 replicates. I called peaks for multiple replicates collectively and also individually. Following are the number of peaks. There is a big difference in peak numbers. Could you please tell me the reason? I am also attaching IGV screenshot of peaks. Thanks in advance looking for a positive response :) 

wc -l *narrowPeak
  111512 control_fibs_1_2_consensus.narrowPeak
   20211 control_fibs_1.narrowPeak
   44189 control_fibs_2.narrowPeak

![peak_difference_bigwiggle](https://user-images.githubusercontent.com/18658412/80824394-ad04e080-8bde-11ea-8bbc-4a74ce00cd01.png)

**Comment by jsh58** [comment]
This is addressed in the [README](https://github.com/jsh58/Genrich/#multiple-replicates) and in #14, #19, #44, #51.

**Comment by Adnanhashim** [comment]
Hi,

Thanks. It's clear now :)
