### ISSUE TITLE
Differential Peak Analysis

### ISSUE THREAD

**Issue by liangcmu** [jsh58/Genrich#57]
We are using Genrich to analyze our ATAC-Seq data.  Here I have a question for your developers: 

Using one treatment A (e.g., with 2 samples) as the control, Genrich can detect significant enrichments of ATAC-Seq peaks (i.e., chromatin opening regions) in a given treatment B (e.g., with 2 samples).   Is this analysis and comparison same as differential peak analysis of peaks between treatments A and B?  We believe that this should be differential peak analysis.  Are we correct? 

We read some publications, most of them only used MACS2 (the previous version of Genrich) to do peak calling, but did not use Genrich for differential peak analysis.  Instead, they got the fragment counts for each peak for individual samples, and then used some tools such as EdgeR, DESeq2, which are the tools originally designed for RNA-Seq analysis, for differential peak analysis.   

We believe Genrich is a better tool for differential peak analysis, and it already has the capability for doing so.   Are we correct in our understanding?  Any comment from you will be highly appreciated.  Why in your document, I can never find "differential peak analysis" at all.   
 
Your help or comment will be highly appreciated. 

John Liang

**Comment by jsh58** [comment]
Thanks for the question.  Genrich was not designed for differential peak calling.  This is not to say it cannot produce reasonable results when used that way.  This may be what you have found.  See #19 for some discussion.

BTW, MACS2 is not "the previous version of Genrich."  They are unrelated.

**Comment by liangcmu** [comment]
I read the thread #19 you pointed.  It seems that control treatment cannot be ATAC-seq data.  I want to double check with you, for our data that have treatment A (two replicates) and treatment B (two replicates), both of them are ATAC-Seq, we **cannot** use Genrich to do differential Peak Analysis by the command like:

Genrich -c A_replicate1.bam, A_replicate2.bam -t  B_replicate1.bam B_replicate2.bam -o revcompare.narrowPeak -j -e chrM -y -d 150 -v

Am I correct?

**Comment by jsh58** [comment]
I will stand by my earlier answer: Genrich was not designed for differential peak calling, but that doesn't mean it cannot produce reasonable results when used that way.
