### ISSUE TITLE
Appropriate area under the curve cut-off for ChIP-seq data 

### ISSUE THREAD

**Issue by HuynhNPT** [jsh58/Genrich#58]
I was wondering if it will be an issue if we're calling TF peaks instead of histone modification peaks? 
In MACS2, there's the option to specify whether we're calling narrow or broad peaks. Therefore, I was wondering if `-a` should be changed when processing TF or HM ChIP-seq. Please advice.

**Comment by jsh58** [comment]
Thanks for the question.  In MACS2, the `--broad` option simply lowers the statistical threshold to *q*< 0.1 and increases the maximum distance between significant sites by a factor of 4.

In Genrich, one can alter the [peak-calling parameters](https://github.com/jsh58/Genrich#peakcalling): the statistical threshold (`-p`/`-q`) and the maximum distance (`-g`).  You can also play with `-a`, although keep in mind that a short peak with high significance may have the same AUC as a large broad peak with low significance.  Finally, you should consider using the [`-P` argument](https://github.com/jsh58/Genrich#pparam) to explore the effects of different peak-calling parameters more efficiently.

**Comment by HuynhNPT** [comment]
Thank you so much for your input. This is a good place for me to start optimizing.
