### ISSUE TITLE
Obtaining differential peaks with genrich replicate mode outputs

### ISSUE THREAD

**Issue by jffchen** [jsh58/Genrich#59]
I have atacseq data and am trying to identify differential open chromatin two groups (control and treatment), each with 2 replicates. However, both replicates in the treatment group has ~25% more reads in the sequencing.  I ran genrich using the replicates function for the two groups using the parameters below: 

Genrich -t controlreplicate1.bam,controlreplicate2.bam -o results.narrowPeak  -k results.bedGraph  -b results.bed  -R results_pcrdup.bed  -j  -y  -r  -e chrM  -m 30

The control group got 20k peaks while the treatment group got 30k peaks. I imagine that such notable difference in sequencing depth and resulting differences in the amount of called peaks would require normalization from the downstream differential open chromatin analysis program for accurate differential peak calling.  I have a couple of questions on how to do that properly: 

1) I've been attempting to do differential peak analysis using diffbind which requires all 4 replicate narrowpeak file and bam files. However, the replicate mode of Genrich outputs a single "merged" narrowpeak file. For Diffbind, would it make sense to input this merged narrowpeak file twice for the 2 replicates?  Or should I run each replicate separately and use that output?  I prefer to use the genrich replicate mode peak files since the genrich replicate mode combines the two replicate's peak pvalue and calls peaks with higher confidence.   However, I'm not sure if inputing the same narrowpeak file for both replicates in Diffbind will skew the analysis.

2) Diffbind also requires the final bam files that's directly used for peak calling. I read from previous posts and from the readme that it's possible to get a list of the removed pcr duplicates so I can process the genrich input bam files to be suitable for diffbind. However, I'm wondering if there is any further modifications or filtering I need to do to the input bam files so that Diffbind has the accurate information needed for normalization.

3) In the genrich replicate mode, does the -R pcr duplicate output file indicate which replicate the PCR duplicate is from?   Or would it be easier if I re-run -R in the separate mode to obtain each replicate's duplicate PCR?

4) In #25 , one suggestion for diff peak calling was to run each replicate separately and then use bedtools merge to identify the consensus and differential peak.  Would this work for the dataset here where I have more reads and more called peaks in one of the groups?

Thanks!

**Comment by jsh58** [comment]
Thanks for the questions.  I do not think it makes sense to use the same peak file twice for two replicates, since that implies that the two replicates produced identical results, which isn't the case.

The removal of PCR duplicates from BAM files is covered in #47.  The question of how DiffBind parses BAM files should be asked to the authors of DiffBind.

**Comment by jffchen** [comment]
Thanks for your help.  

Is it correct to say that the final modified data that's directly inputed into the peak calling portion of Genrich (using options  -R -j -y -r -e chrM -m 30) is the same as if I took the original Genrich inputted .bam files and removed the -R PCR duplicates and all mito reads?  Would I also have to remove the reads filtered out with the "-m 30" option  (via samtools view -q 30)?

**Comment by jsh58** [comment]
Yes, you should also remove the alignments with MAPQ<30 via `samtools view -q30`.
