### ISSUE TITLE
Sample has no analyzable fragments 

### ISSUE THREAD

**Issue by JulieHoang** [jsh58/Genrich#6]
How should I trouble shoot this? I have tried two other bam files (both has alignment of 95% by HISAT2)
 ./Genrich -t SRR7650775_pass.bam -o naive.narrowPeak -r -e chrM -j -v 
Processing experimental file #0: SRR7650775_pass.bam
  BAM records analyzed:  112372379
    Unmapped:              5341429
    Paired alignments:   102179406
      secondary alns:     17803420
      "orphan" alns:     102179406
    Unpaired alignments:   4851544
      secondary alns:      1218577
  PCR duplicates --
    Paired aln sets:             0
      duplicates:                0 (0.0%)
  Fragments analyzed:            0
    Full fragments:              0
Error! Experimental sample has no analyzable fragments

**Comment by jsh58** [comment]
Thanks for the question.  It appears from the log file that *all* of the paired alignments were orphans, meaning that the pairs could not be matched up (see the last item [here](https://github.com/jsh58/Genrich#warning)).  That is why there were no analyzable fragments.

If you post the first few lines of the BAM file, we may be able to determine what the issue is.  `samtools view SRR7650775_pass.bam | head -n4`

**Comment by JulieHoang** [comment]
Hi, 
Thank you for your answer. Indeed, it is the problem since we tried running with -y option and it works. 
Here is the lines from the BAM file
SRR7650733.1.1	99	6	96521774	60	76M	=	96521848150	CCNCTTGTCCCTCTGCGCGGCCCGTTCCGCCTCTCTTCTCCCACCGCCTGTCGGCTGACGTGTCTGCAGTTCCTCC	AA#F<JJFJJJAFJJJJJFJJJJJJJJJAJJ-7--AAA-AFJ<JJ7J<7A-AFJ--7FAA-7AFFJFJJJJJJF-F	AS:i:-2	ZS:i:-3	XN:i:0	XM:i:1	XO:i:0	XG:i:0	NM:i:1	MD:Z:2T73	YS:i:-6	YT:Z:CP	NH:i:1
SRR7650733.1.2	147	6	96521848	60	76M	=	96521774-150	CCGCGTCTACTGCGAGTCAGGCCGTGATGGCGGACGCCTGCGAAGCGATTAGGCGGTTGGCGGCCGACTTCCAGCG	FFAAJFF<J<JJAF7F7--<AF<F<A-JJJFJA7FAA7AF-F<F<-AAFF7FJJJJJJJJJJJJAJFJJJJF-<-A	AS:i:-6	XN:i:0	XM:i:2	XO:i:0	XG:i:0	NM:i:2	MD:Z:40G4A30	YS:i:-2YT:Z:CP	NH:i:1
SRR7650733.2.1	83	3	120095641	60	35M	=	120095641	-35	CATTGATACAGAGGCTTGCTGCGCTTGGTGTGNGC	<AJJFAJJJJJ<JJAJJJJJJJJFFJF<FJFF#AA	AS:i:-2	ZS:i:-4	XN:i:0	XM:i:1	XO:i:0	XG:i:0	NM:i:1	MD:Z:32C2	YS:i:0	YT:Z:CP	NH:i:1
SRR7650733.2.2	163	3	120095641	60	35M	=	120095641	-35	CATTGATACAGAGGCTTGCTGCGCTTGGTGTGCGC	AAFFFJJJJJFAJ<JF--AFJJJJ--7AFJ7-7JJ	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:35	YS:i:-2YT:Z:CP	NH:i:1

**Comment by jsh58** [comment]
The issue here is that the first fields of the SAM records of the paired reads do not match.  For example, the first two reads, which are aligned in a proper pair, are listed as `SRR7650733.1.1` and `SRR7650733.1.2`.  Instead, both reads ought to have the same `SRR7650733.1` there, to indicate that they came from the same template (see the [SAM spec](https://samtools.github.io/hts-specs/SAMv1.pdf) for the description of `QNAME`).  Since they don't match, Genrich doesn't pair them together, and counts them as orphans.

I don't know why your BAM file is formatted like that, but bringing the BAM file up to spec will allow Genrich to analyze all the reads correctly.

**Comment by doliv071** [comment]
I'm also getting this error. However, in my case it seems that the alignments are correctly named. 

```Genrich -j -l 50 -v -q 0.001 -t Sample_Ruoxi6928_2019_02_22.bam -o Sample_Ruoxi6928_2019_02_22.narrowPeak
Processing experimental file #0: Sample_Ruoxi6928_2019_02_22.bam
  BAM records analyzed:   32183602
    Paired alignments:    31387862
      "orphan" alns:      31387862
    Unpaired alignments:    795740
  Fragments analyzed:            0
    Full fragments:              0
    ATAC-seq cut sites:          0
      (expanded to length 100bp)
Error! Experimental sample has no analyzable fragments
```

The first set 2 pairs from the bam...

```
K00237:97:H55NTBBXY:2:1101:1103:1578	99	chr17	7205023	44	50M	=	7205033	55	CGCNAGCCCCGCCTCTCCTGCCCTGGGCCCCGCCCCACGTTAGCCAGGCC	AAF#FJJJJJ<FJJJAFJJJJJJJFJFFJJJJJJJJJJJFFJ7JJJ<FJJ	AS:i:97	XN:i:0	XM:i:1	XO:i:0	XG:i:0	NM:i:1	MD:Z:3T46	YS:i:85	YT:Z:CP	MQ:i:44	MC:Z:50M	ms:i:1346
K00237:97:H55NTBBXY:2:1101:1103:1578	147	chr17	7205028	44	50M	=	7205028	-55	GNCNCGCCTCTCCTGCCCNGNGCCCCGCCCCACGTTAGCCAGGCCGNGAG	<#-#A7--AAJJJJJF7J#J#JFF-7FAJJFA7J<F-JFA-JJFJF#A-A	AS:i:85	XN:i:0	XM:i:5	XO:i:0	XG:i:0	NM:i:5	MD:Z:1C1C14T1G25A3	YS:i:97	YT:Z:CP	MQ:i:44	MC:Z:50M	ms:i:1895
K00237:97:H55NTBBXY:2:1101:1103:2422	99	chr6	32854566	42	50M	=	32854587	66	CTTNCGCTTTCACTCTGGTCCCGGACAGTGGGGGCTGGTTAAATCAAGAA	AAA#FJJJFJJJJJJFJJJJJJJJJJJFFJFFFJJ<<AAFJJJJJAJJJJ	AS:i:97	XN:i:0	XM:i:1	XO:i:0	XG:i:0	NM:i:1	MD:Z:3T46	YS:i:80	YT:Z:CP	MQ:i:42	MC:Z:50M	ms:i:1427
K00237:97:H55NTBBXY:2:1101:1103:2422	147	chr6	32854582	42	50M	=	32854571	-66	GNTNCCGGACAGTGGGGGNTNGTTAAAGCAAGAAAGGGGGTTGGGGNTGG	F#7#-FJFA-AFJJJJJF#J#F<F<-<-AFAF77AJJJJJ7<JJJ<#AAA	AS:i:80	XN:i:0	XM:i:6	XO:i:0	XG:i:0	NM:i:6	MD:Z:1G1C14C1G6T18A3	YS:i:97	YT:Z:CP	MQ:i:42	MC:Z:50M	ms:i:1891
```

Thanks for the help. Seems like a great program, would really like to transition to it if possible :)

**Comment by jsh58** [comment]
In this case, the `PNEXT` fields do not match the `POS` fields of the pairs (again, see the [SAM spec](https://samtools.github.io/hts-specs/SAMv1.pdf) for details).  Your SAM records *should* be (assuming the `POS` fields are correct):
```
K00237:97:H55NTBBXY:2:1101:1103:1578	99	chr17	7205023	44	50M	=	7205028	55	CGCNAGCCCCGCCTCTCCTGCCCTGGGCCCCGCCCCACGTTAGCCAGGCC	AAF#FJJJJJ<FJJJAFJJJJJJJFJFFJJJJJJJJJJJFFJ7JJJ<FJJ	AS:i:97	XN:i:0	XM:i:1	XO:i:0	XG:i:0	NM:i:1	MD:Z:3T46	YS:i:85	YT:Z:CP	MQ:i:44	MC:Z:50M	ms:i:1346
K00237:97:H55NTBBXY:2:1101:1103:1578	147	chr17	7205028	44	50M	=	7205023	-55	GNCNCGCCTCTCCTGCCCNGNGCCCCGCCCCACGTTAGCCAGGCCGNGAG	<#-#A7--AAJJJJJF7J#J#JFF-7FAJJFA7J<F-JFA-JJFJF#A-A	AS:i:85	XN:i:0	XM:i:5	XO:i:0	XG:i:0	NM:i:5	MD:Z:1C1C14T1G25A3	YS:i:97	YT:Z:CP	MQ:i:44	MC:Z:50M	ms:i:1895
K00237:97:H55NTBBXY:2:1101:1103:2422	99	chr6	32854566	42	50M	=	32854582	66	CTTNCGCTTTCACTCTGGTCCCGGACAGTGGGGGCTGGTTAAATCAAGAA	AAA#FJJJFJJJJJJFJJJJJJJJJJJFFJFFFJJ<<AAFJJJJJAJJJJ	AS:i:97	XN:i:0	XM:i:1	XO:i:0	XG:i:0	NM:i:1	MD:Z:3T46	YS:i:80	YT:Z:CP	MQ:i:42	MC:Z:50M	ms:i:1427
K00237:97:H55NTBBXY:2:1101:1103:2422	147	chr6	32854582	42	50M	=	32854566	-66	GNTNCCGGACAGTGGGGGNTNGTTAAAGCAAGAAAGGGGGTTGGGGNTGG	F#7#-FJFA-AFJJJJJF#J#F<F<-<-AFAF77AJJJJJ7<JJJ<#AAA	AS:i:80	XN:i:0	XM:i:6	XO:i:0	XG:i:0	NM:i:6	MD:Z:1G1C14C1G6T18A3	YS:i:97	YT:Z:CP	MQ:i:42	MC:Z:50M	ms:i:1891
```

I don't know which aligner you used, but I do not think you will have this problem with [Bowtie2](http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml).

**Comment by doliv071** [comment]
Thanks for the quick response John. It seems that my script for adjusting for the tn5 cutsite offset needs to be fixed. Do you recommend perform the tn5 adjustment before peak calling or after?

**Comment by jsh58** [comment]
I don't understand what you're trying to do.  If you are using Genrich in ATAC-seq mode, you can read the description of how alignments are interpreted [here](https://github.com/jsh58/Genrich#atacseq).

**Comment by doliv071** [comment]
Sorry, I wasn't very clear in what I meant by "tn5 adjustment". As far as I can tell the consensus is that before doing peak calling read alignments should be shifted 4 or 5 bases to account for the length of the tn5 binding site (9bp meaning that the DNA had to be accessible at least 4.5bp on either site of the insertion). 

So my question was whether you thought this type of adjustment should be done before calling peaks with Genrich. 

I realize this is only tangentially related to this particular issue so I apologize for hijacking this thread.

**Comment by jsh58** [comment]
If you want 9bp cut site intervals to be interpreted, then you can run `-j -d 9`.  Other than that, no other alignment adjustments are performed by Genrich, and anything that brings the SAM/BAMs out of spec is certainly not recommended.

**Comment by jsh58** [comment]
... and, any program that **does** analyze an out-of-spec SAM/BAM is to be avoided.

**Comment by mdozmorov** [comment]
@jsh58, the "Error! Experimental sample has no analyzable fragments" occurs in data aligned by different aligners. The `subread-align` alignment:
````
J00167:207:H53VLBBXY:6:1101:1316:11513  16      chr11   26609579        20      9S35M   *       0       0       CTAAGAAGTCTGCCTGTTATGTGGTCACAATGACTCTCAGCAAA    <F<<<-77-A<JJFFFF-F-<JJJAFFAAFJFAFA7-7JFF<<<    HI:i:1  NH:i:1  NM:i:1
J00167:207:H53VLBBXY:6:1101:1316:15627  4       *       0       0       *       *       0       0       TCTATCTATCTATCTATCTATCTATCTATCTCTCTATCTATCTATCATCT      AA--A7F-F<F<FFFA<FFF<7FFJ<A7-FJ-<7FF-<<J<--<F-F<-<
J00167:207:H53VLBBXY:6:1101:1326:2316   16      chr15   47489007        20      48M     *       0       0       AAGAAAGAACAGAGATAGAAAGACCAAAGAAAGAAGGAGAGAAAGAGG        J-F<A--7A<AFA7-7F-A<AAA-FF<A-7FFFJJJJJJAAAAAA-<<        HI:i:1  NH:i:1  NM:i:1
J00167:207:H53VLBBXY:6:1101:1326:20639  16      chr8    48252632        40      1S47M   *       0       0       GCCTGTGTATATCTGTGTGTATACCACTGACTCGAGTGTGTGTCTGTT        7JA<--<F-7-JF-AJFJAF7<<-JAFA7JFAF<7-<AA<F7F-A<AA        HI:i:1  NH:i:1  NM:i:0
````
and the `STAR` alignment:
````
J00167:207:H53VLBBXY:6:1101:1316:11513  16      chr11   26609570        255     44M     *       0       0       CTAAGAAGTCTGCCTGTTATGTGGTCACAATGACTCTCAGCAAA <F<<<-77-A<JJFFFF-F-<JJJAFFAAFJFAFA7-7JFF<<<    NH:i:1  HI:i:1  AS:i:37 nM:i:3
J00167:207:H53VLBBXY:6:1101:1316:15627  0       chr10   96676650        3       50M     *       0       0       TCTATCTATCTATCTATCTATCTATCTATCTCTCTATCTATCTATCATCT   AA--A7F-F<F<FFFA<FFF<7FFJ<A7-FJ-<7FF-<<J<--<F-F<-<      NH:i:2  HI:i:1  AS:i:49 nM:i:0
J00167:207:H53VLBBXY:6:1101:1316:15627  272     chr4    23880732        3       50M     *       0       0       AGATGATAGATAGATAGAGAGATAGATAGATAGATAGATAGATAGATAGA   <-<F-F<--<J<<-FF7<-JF-7A<JFF7<FFF<AFFF<F<F-F7A--AA      NH:i:2  HI:i:2  AS:i:49 nM:i:0
J00167:207:H53VLBBXY:6:1101:1326:2316   16      chr15   47489007        255     48M     *       0       0       AAGAAAGAACAGAGATAGAAAGACCAAAGAAAGAAGGAGAGAAAGAGG     J-F<A--7A<AFA7-7F-A<AAA-FF<A-7FFFJJJJJJAAAAAA-<<        NH:i:1  HI:i:1  AS:i:45 nM:i:1
````

Both result in the same error. This is single-end alignment, ChIP-seq sequencing.

flagstat for each file:
````
42262492 + 0 in total (QC-passed reads + QC-failed reads)
6749554 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
42262492 + 0 mapped (100.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
````
and 
````
39092159 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
33043819 + 0 mapped (84.53% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
````

I saw your comment "the PNEXT fields do not match the POS fields of the pairs." But the specs also say about PNEXT - "Set as 0 when the information is unavailable." So, I don't see an obvious error, still, Genrich fails. Any ideas? Thank you.

**Comment by jsh58** [comment]
> This is single-end alignment, ChIP-seq sequencing.

Genrich does not analyze single-end alignments by default, as described [here](https://github.com/jsh58/Genrich#alignment).  To analyze them, you must set one of the three options described [here](https://github.com/jsh58/Genrich#unpaired).

**Comment by mdozmorov** [comment]
I overlooked this in the documentation. Will try. Thanks, @jsh58
