### ISSUE TITLE
Convert BedGraph-ish files to BedGraph files

### ISSUE THREAD

**Issue by matwgmkw** [jsh58/Genrich#61]
Hi. Thanks for this nice software.

I am wondering after obtaining the BedGraph-ish files of the ATAC-seq signal pileups, how to convert them to BedGraph files (which column to extract)? I have to extract the first four columns to a new file, is that right?

There are 6 columns in the file:
chr, start, end, experimental, control and -log(p)

Thanks.

**Comment by jsh58** [comment]
Thanks for the question.  The descriptions of the columns of such files is given [in this section](https://github.com/jsh58/Genrich#optional).  The question of which column to extract depends entirely on what information you are trying to collect and examine.
