### ISSUE TITLE
Narrow and Broad Peaks

### ISSUE THREAD

**Issue by Carmelo-Bravo** [jsh58/Genrich#65]
Hi, I want to use Generich to analyze my single end CHIPseq data.
I have different type of CHIPseq experient (TFs and Histon Markers like H3K9me3 or H3K4me3).
I was wondering if I can call the different types of peaks (narrow and broad) using Generich and, if not, how I can discriminate narrow peaks from broad peaks using Generich.

Thanks!

**Comment by jsh58** [comment]
Thanks for the question.  I recommend that you examine the [peak-calling parameters](https://github.com/jsh58/Genrich#peakcalling) of Genrich and the information contained in the output file (described in the `-o <file>` section [here](https://github.com/jsh58/Genrich#required).  There is also some discussion of this topic in #58.

**Comment by Carmelo-Bravo** [comment]
Thanks for the information and for your help.
