### ISSUE TITLE
Error code: "SAM/BAM file not sorted by queryname (samtools sort -n)"

### ISSUE THREAD

**Issue by ydchung15** [jsh58/Genrich#68]
Hi, 
I got an error code with ""SAM/BAM file not sorted by queryname (samtools sort -n)", although all my bam files were properly sorted. When i tried stdin as the input file using a pipe (samtools sort -n <my_bam.bam> | Genrich -t - -o <out_file>) , I got an error code with "Cannot pipe in gzip-compressed file (use zcat instead)". Thus I used samtools output option to the SAM format (adding '-O SAM' option to the samtools sort command), I finally got the narrowPeak file! 

It seems likely to me that the Genrich cannot handle bam files at all in my system. Could you please tell me how can I fix this problem? Thanks in advance!

**Comment by ydchung15** [comment]
I found my bam files had problems.  After resorting the bam files, everything worked fine.

**Comment by Castel-Tao** [comment]
May I ask what issues you encountered with the BAM file? I have encountered the same problem
