### ISSUE TITLE
bedgraphs normalization

### ISSUE THREAD

**Issue by sunta3iouxos** [jsh58/Genrich#71]
Hi,
Are the outputted bedgraph files normalized? and if yes which method is used? Can I use the bedgraph files to calculate coverage in the resulting peaks?

**Comment by jsh58** [comment]
The values for the experimental pileup in the bedgraph-ish output file are not normalized, and the calculation of control pileup values is described [here](https://github.com/jsh58/Genrich#pileup).  The meaning of "coverage in the resulting peaks" is not clear.

**Comment by sunta3iouxos** [comment]
Thank you for the answer, I will try to readdress my questions.
for the meaning of coverage: I would like to use normalized bedgraphs to plot the average profile of common peaks found with Genrich (intersecting peaks discovered in different conditions).
Regarding the normalization,
A. till now I am using deeptools to normalize my bedgraphs across the samples (she above for an application) and I was wondering if you could provide an inherited option to save normalized bedgraphs for all replicates and possible inputs.
B.will this produce normalized counts across the samples:
  -k  <file>       Output bedgraph-ish file for pileups and p-values
    For each replicate, sequentially, this file lists a header line (# experimental file: <name>; control file: <name>), followed by experimental/control pileups and a p-value for each interval. This is the way to examine pileup values with multiple replicates, since the -f log file does not supply them in that case. 

Many thanks for your time

**Comment by jsh58** [comment]
No, the experimental pileup values in both the `-f` and `-k` bedgraph-ish output files are not normalized.  The purpose of these files is to allow users to understand the details of how peaks were called for their samples.  There are no plans to change the files' formats.

**Comment by sunta3iouxos** [comment]
many thank for your answers. I do hope that at some point you'll implement a normalized bdg-ish ouput.
