### ISSUE TITLE
Discordant alignments and -y option in PE ATAC-Seq experiment

### ISSUE THREAD

**Issue by uli-arb** [jsh58/Genrich#77]
Hello, 

I'm not sure if this is the best place to ask this, but I'm not sure about when to include discordant or half-alignments during peak calling. Is the -y option intended for mainly single-end processing? In what kind of situations would only one of the PE reads be aligning to the genome? Thank you for your help and developing Genrich!

**Comment by jsh58** [comment]
Thanks for the question.  The `-y` (or `-w <int>`) option is *required* to analyze single-end reads, but certainly can be used with paired-end reads as well.  Paired-end reads may have excessive unpaired alignments under a variety of circumstances, such as low-quality reads (often R2), or an incomplete reference genome.
