### ISSUE TITLE
peak calling with repeats

### ISSUE THREAD

**Issue by 809825706** [jsh58/Genrich#78]
Hi, thank you for such a great tools for ATACseq. I was using this tool for few months. in which, I found some strange results. I was foused about them, so I write this issue for asking for you help.

1. When combining mutiple sample(repeats), there are more peaks than calling peaks with any one of them. if calling peak with repeats, should there be less peaks which is more universal in all repeats?

![peaks](https://user-images.githubusercontent.com/46601791/126860684-9c0b9894-ab94-47bd-afe9-93f60ac4b8e3.png)

2. is the output file standard narrowpeaks file? the qvalue in all my narrowpeaks is -1.

![narrowpeak](https://user-images.githubusercontent.com/46601791/126860798-b5050782-32f0-4a48-94e6-855c9df8a339.png)

all peak was calling use:
`Genrich  -t ${treat}.bam  -o ${out}/${name}.narrowPeak -j -y -r -m 30 -e MT  -v`

**Comment by jsh58** [comment]
Your first question is addressed in the [README](https://github.com/jsh58/Genrich/#multiple-replicates) and in #14, #19, #44, #51, #56, #64.

Your second question is addressed in #41.

**Comment by 809825706** [comment]
> Your first question is addressed in the [README](https://github.com/jsh58/Genrich/#multiple-replicates) and in #14, #19, #44, #51, #56, #64.
> 
> Your second question is addressed in #41.

thank you for your answer! with the limit to q-value(< 0.05), the peaks number was reduced significantly.

![Genrich-pvalue](https://user-images.githubusercontent.com/46601791/127122355-f4c913bf-c322-4259-8e6d-d5cad3b9c9a0.png)

![g3412](https://user-images.githubusercontent.com/46601791/127125374-663095c5-ed42-42ff-bd40-9abef4f7f6af.png)

while the (combine) peaks from multiple repeats is more than the single repeat and the common peaks which is the overlapped in the single repeat results. the common peak was got just like the way that IDR does, which find out the sharing peaks in single repeat with loosing limit p-value. I have looked over issues you mentioned above. I think they can't answer my confusion. although Genrich can call peaks with multiple repeats, the results of it seem not equal to IDR.  Or with multiple repeats, there should be smaller P-value limit?

**Comment by jsh58** [comment]
> although Genrich can call peaks with multiple repeats, the results of it seem not equal to IDR.

Genrich does not use IDR to call peaks with multiple repeats, as explained [here](https://github.com/jsh58/Genrich#multiple-replicates).
