### ISSUE TITLE
single end data ATAC-seq mode

### ISSUE THREAD

**Issue by ShuangHe33** [jsh58/Genrich#8]
Hi,thank you for the great software. According  to your manual, I'm wondering that is it appropriate to apply  -j -y mode to single-end ATAC-seq data(51 bp) since only one cut site of a read can be provided ? Now  I have two replicates , one is paired-end and the other one is single-end ,  I'm worried that it will find more peaks in the paied-end ATAC-seq data than the single-end data use -j -y mode.  Could you please give me some advice? Thank you in advance.

**Comment by jsh58** [comment]
First of all, with single-end reads, you *must* specify `-y` for any intervals to be interpreted.  Yes, only one interval will interpreted with single-end reads; half as many as with paired-end reads, but the background will also be half as much.  So there won't necessarily be more peaks with paired-end reads.  The best suggestion is try it out and see what happens.

**Comment by ShuangHe33** [comment]
Hi, I applied Genrich to one of my  single-end ATAC-seq data with '-y -j -d 100 ' and it detected 28757 peaks while the number of peak was 37675 performed by MACS1.4 (default parameters).  Usually Genrich can find more peaks of paired-end ATAC-seq data (with parameters '-y -j -d 100') compared to MACS1.4 (default parameters) according to my experience.  Hope this information is helpful.
