### ISSUE TITLE
"poorly formatted BED record" error on bed6 format

### ISSUE THREAD

**Issue by lengie** [jsh58/Genrich#81]
Hello, I am calling GenRich with a bedfile input of genomic locations to exclude. 

```
maxBtwPeaks=2000
coding=file.bed
pval=0.01
Genrich -t replicate1.primary.bam,replicate2.primary.bam -y -v -p $pval -E $coding -g $maxBtwPeaks -o sox10_GenRichPval01.narrowPeaks
```

I am inputting bed files with 6 columns (chr, start, end, ID, score, strand) that have no column or row names and are tab delimited. I have tried both UCSC and Ensembl format. I get this error but it is unclear how GenRich wants the BED files formatted. Any tips?

```
Error! chr1 50321633 50322231 NM_131426_exon_0_0_chr1_50321634_f 1 +
: poorly formatted BED record
```

```
Error! 1 50321633 50322231 NM_131426_exon_0_0_chr1_50321634_f 1 +
: poorly formatted BED record
```

I've also tried with a bed 3 file
```
Error! chr1 50321633 50322231
: poorly formatted BED record
```

**Comment by jsh58** [comment]
From what I can see in the error message, it does not look like the BED records are tab-delimited.  Please double-check that.  If that is not the issue, please post (part of) the BED file here and I will have a look.

**Comment by lengie** [comment]
You're right, this was the issue. Looks like this parameter was left out when making the bed files though I thought they were tab-delimited.
