### ISSUE TITLE
ATAC-seq pipeline

### ISSUE THREAD

**Issue by LunaPatton** [jsh58/Genrich#82]
Hi!
Recently, I'm working on ATAC-seq pipeline with Genrich, here are my questions: @jsh58 
1. When peaks calling, should I remove sex chromosome (e.g., chr.X) as well? 
2. MACS2 seems to be more pervasive when deal with Chip-seq or ATAC-seq data. I'm also trying to merge the pipeline recommond by ENCODE with Genrich and compare these two softwares (i.e., Genrich and MACS2) to find the pros and cons. As far as I'm concerned, Genrich is more flexible and manipulable. And I hope to receive more feedback or suggestions about it.

Many thanks !
Zoe

**Comment by LunaPatton** [comment]
And I also not quite sure about "multiple replicates". So if I use below code:

_Genrich -t $rep1 $rep2 $rep3 -o rep.narrowPeak -f rep.log -j -y -r -m 30 -e chrM,chrX -b rep.bed_

Is that peak calling on individual samples first, and then aggregated multi-sample peak calling for each group? Whether that *.narrowPeak file has already contained joint-calling result? @jsh58

**Comment by jsh58** [comment]
I invite you to read the [ATAC-seq Guidelines](https://informatics.fas.harvard.edu/atac-seq-guidelines.html) that I wrote, and the [Genrich README](https://github.com/jsh58/Genrich#replicate) which details the peak-calling process for multiple replicates.
