### ISSUE TITLE
About ATAC-seq peakcalling

### ISSUE THREAD

**Issue by ChunjieJiang** [jsh58/Genrich#84]
Hi 

Genrich is a wonderful tool for ATAC-seq data. I have used it in my cell metabolism paper (DOI: 10.1016/j.cmet.2021.06.004). And I'll used it again in my new project. 

I have one question about the peak calling. I was told by other senior analyzer that only nucleosome-free (NFR) reads should be considered for peak calling. Does Genrich containing steps to remove Mono nucleosome reads and Nucleosome reads, and do peak calling only using nucleosome-free (NFR) reads?

**Comment by jsh58** [comment]
Thanks for the question.  There is no option in Genrich to filter fragments based on size.  While it is true that ATAC-seq fragments follow a characteristic size distribution, it is *not* the case that **all** fragments above a certain size (~150bp) are derived from DNA segments surrounding one or more nucleosomes.  I do not know of a method to separate reads derived from longer fragments into those that surrounded nucleosomes versus those that did not.

**Comment by ChunjieJiang** [comment]
Hi John,

Thanks for your reply.

Best wishes,
Chunjie
