### ISSUE TITLE
Peak summit

### ISSUE THREAD

**Issue by wangxiangxiu** [jsh58/Genrich#87]
Hello, I'm trying Genrich to call peaks for ATAC-seq data.
When doing motif finding and peak annotation, the peak summit file is needed, so I'm wonder how may I get the peak summit information from Genrich result files?
Thanks a lot.

**Comment by jsh58** [comment]
Thanks for the question.  I am unsure what "peak summit information" you need, but the format of all output files is described in detail [here](https://github.com/jsh58/Genrich#required).
