### ISSUE TITLE
Number of peaks fall after including input DNA control

### ISSUE THREAD

**Issue by keenhl** [jsh58/Genrich#94]
When I include the input DNA control (-c option), I only get a few hundred called peaks.  However,  leaving all the other parameters the same, if I do not include the input DNA, the number of peaks goes up about 10 fold.  Is this expected, that the number of peaks would fall so much after including the input DNA control?

Thanks for your help.

**Comment by jsh58** [comment]
It is expected that specifying a control sample will increase the control pileup value at some genomic positions, and thus result in fewer peaks.  Beyond that, I cannot comment on the particulars of your experiment.
