### ISSUE TITLE
Description of the -v option

### ISSUE THREAD

**Issue by Le1223** [jsh58/Genrich#96]
This is what the -v option shows
![1660704038940](https://user-images.githubusercontent.com/91594515/185022678-7a23db48-b91a-4fe5-a09e-9af1c90ca7ee.png)

Excuse me, what does "Supp./dups/lowQual" mean

**Comment by jsh58** [comment]
That label indicates that the alignment record is either supplementary, a PCR duplicate, or low quality, and thus is not further analyzed by Genrich.  More information about the bitwise FLAG can be found in the [SAM specification](https://samtools.github.io/hts-specs/SAMv1.pdf).
