### ISSUE TITLE
program failed

### ISSUE THREAD

**Issue by lmanchon** [jsh58/Genrich#98]
--Hi,
the program failed with:
Genrich -t DGV_chr20.bam -c chr20.bam -o DGV_chr20_hg38.peaks -f DGV_chr20_hg38.log -q 0.05 -a 20.0 -v

Processing experimental file #0: DGV.bam
  BAM records analyzed:     5751753
    Paired alignments:            0
    Unpaired alignments:    5751753
      secondary alns:        420303
  Fragments analyzed:             0
    Full fragments:               0
Error! Experimental sample has no analyzable fragments

my experimental bam contains only 50bp single-end reads. 

thank you --

**Comment by jsh58** [comment]
Genrich analyzes only paired alignments by default, as described [here](https://github.com/jsh58/Genrich#unpaired) and also #8 and #24.  For single-end reads, you must specify either `-y` or `-w <int>`.
