### ISSUE TITLE
Can I use Genrich to call peaks from m6A (MeRIP)-seq data?

### ISSUE THREAD

**Issue by zhiyi1988** [jsh58/Genrich#99]
Hi there,

Thanks for developing Genrich!

Recently I got some m6A-seq data and I'm trying to process it with Genrich. As m6A-seq involves immunoprecipitation of ~100 nt-long RNA fragments using m6A-specific antibodies, whose principle is similar to ChIP-seq, I think maybe Genrich can also be used to process m6A-seq data.

However, since the sequenced fragment is shorter, and involves splicing, I'm not sure if the performance of Genrich will be influenced, and if any specific parameter settings (e.g. -r, -a, -l, -g) should be take care of? 

The settings I'm using is as follows,
sample=$1
Genrich -t ./ZY${sample}.sorted_genrich.bam -o ZY${sample}ip.narrowPeak -f ZY${sample}ip.log \
-c ./ZY${sample}input.sorted_genrich.bam -b ZY${sample}ip.bed \
-r -y -v \
-q 0.05 -a 20.0

Is this appropriate? Any advice  would be much appreciated. 

Regards, Zhiyi

**Comment by jsh58** [comment]
Thanks for the question.  I am unsure how well Genrich can analyze MeRIP-seq data.  My suggestion is to examine the `-b <file>` and see if Genrich is interpreting the alignments correctly.

**Comment by zhiyi1988** [comment]
> Thanks for the question. I am unsure how well Genrich can analyze MeRIP-seq data. My suggestion is to examine the `-b <file>` and see if Genrich is interpreting the alignments correctly.

Thank you for the reply! I'll take a look at the output.
